/**
 * summarizetube/youtube — caption extraction without binaries.
 *
 * Strategy (pure JS, Workers-compatible):
 *   1. Parse the video id out of any YouTube URL shape.
 *   2. GET the watch page and pull `ytInitialPlayerResponse` (brace-matched
 *      JSON embedded in a script tag).
 *   3. Pick the best caption track (manual > ASR, user language first).
 *   4. Fetch the timedtext track and parse it (json3 or legacy XML).
 *
 * Everything network goes through an injected `fetch` impl so tests run
 * offline. YouTube changes this surface without notice: every step degrades
 * to `null` and the caller replies with an honest failure.
 */

export interface CaptionCue {
  /** seconds */
  start: number;
  /** seconds */
  duration: number;
  text: string;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  /** "asr" = auto-generated by speech recognition */
  kind?: string;
}

export interface PlayerResponse {
  videoDetails?: {
    title?: string;
    author?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
}

const YT_HOSTS = new Set([
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "music.youtube.com",
  "youtu.be",
  "www.youtu.be",
  "youtube-nocookie.com",
  "www.youtube-nocookie.com",
]);

export const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;

/**
 * Extract the 11-char video id from any common URL shape
 * (watch?v=, youtu.be/, shorts/, embed/, live/) or a bare id.
 */
export function parseVideoId(input: string): string | null {
  const raw = input.trim();
  if (VIDEO_ID_RE.test(raw)) return raw;
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  if (!YT_HOSTS.has(url.hostname.toLowerCase())) return null;
  if (url.hostname.toLowerCase().endsWith("youtu.be")) {
    const id = url.pathname.split("/").filter(Boolean)[0] ?? "";
    return VIDEO_ID_RE.test(id) ? id : null;
  }
  const vParam = url.searchParams.get("v");
  if (vParam && VIDEO_ID_RE.test(vParam)) return vParam;
  const parts = url.pathname.split("/").filter(Boolean);
  // /shorts/<id>, /embed/<id>, /live/<id>, /v/<id>
  if (parts.length >= 2 && ["shorts", "embed", "live", "v"].includes(parts[0]!)) {
    const id = parts[1]!;
    return VIDEO_ID_RE.test(id) ? id : null;
  }
  return null;
}

/**
 * Tolerant JS-literal -> JSON converter. Real watch pages embed
 * ytInitialPlayerResponse as a JS object literal: unquoted keys, stray
 * trailing commas. This walks the object string-aware and quotes bare
 * keys / strips trailing commas so JSON.parse accepts it.
 */
export function normalizeJsObject(src: string): string {
  let out = "";
  let inString = false;
  let escaped = false;
  for (let i = 0; i < src.length; i++) {
    const ch = src[i]!;
    if (inString) {
      out += ch;
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    // Quote bare identifiers that act as object keys ("foo": vs labels).
    const rest = src.slice(i);
    const keyMatch = /^([A-Za-z_$][\w$]*)(\s*:)/.exec(rest);
    if (
      keyMatch &&
      keyMatch[1] !== "true" &&
      keyMatch[1] !== "false" &&
      keyMatch[1] !== "null"
    ) {
      out += `"${keyMatch[1]}"${keyMatch[2]}`;
      i += keyMatch[0].length - 1;
      continue;
    }
    // Strip a trailing comma before } or ].
    const trailMatch = /^(,\s*)([}\]])/.exec(rest);
    if (trailMatch) {
      out += trailMatch[2]!;
      i += trailMatch[0].length - 1;
      continue;
    }
    out += ch;
  }
  return out;
}

/** Brace-match the LAST ytInitialPlayerResponse assignment in the page.
 *
 * Real watch pages define the object several times (early placeholder, then
 * the populated one); the last assignment is the authoritative one. */
export function extractPlayerResponse(html: string): PlayerResponse | null {
  const marker = "ytInitialPlayerResponse";
  let found: PlayerResponse | null = null;
  let from = 0;
  while (true) {
    const idx = html.indexOf(marker, from);
    if (idx === -1) return found;
    const start = html.indexOf("{", idx);
    if (start === -1) return found;
    // Guard against markers appearing inside unrelated strings/keys where
    // the next "{" belongs to some other construct far away.
    if (start - idx > marker.length + 40) {
      from = idx + marker.length;
      continue;
    }
    const json = sliceBalancedObject(html, start);
    if (!json) {
      from = idx + marker.length;
      continue;
    }
    try {
      found = JSON.parse(normalizeJsObject(json)) as PlayerResponse;
      // Keep scanning: later assignments override earlier placeholders.
      from = idx + marker.length + json.length;
    } catch {
      from = idx + marker.length;
    }
  }
}

/** Return the balanced `{...}` slice starting at `openBrace`, or null. */
function sliceBalancedObject(html: string, openBrace: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = openBrace; i < html.length; i++) {
    const ch = html[i]!;
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return html.slice(openBrace, i + 1);
    }
  }
  return null;
}

export type TrackPreference = readonly string[];

/**
 * Choose the caption track: manual tracks beat ASR; within each class,
 * follow the preference order (e.g. ["pt-BR", "pt", "en"]); else first track.
 */
export function pickCaptionTrack(
  tracks: readonly CaptionTrack[],
  preference: TrackPreference = ["pt-BR", "pt", "en"],
): CaptionTrack | null {
  if (!tracks.length) return null;
  const score = (t: CaptionTrack): number => {
    const manual = t.kind === "asr" ? 1 : 0; // lower wins
    const prefIdx = preference.findIndex((p) =>
      t.languageCode.toLowerCase() === p.toLowerCase() ||
      t.languageCode.toLowerCase().split("-")[0] === p.toLowerCase().split("-")[0],
    );
    return manual * 100 + (prefIdx === -1 ? 50 : prefIdx);
  };
  return [...tracks].sort((a, b) => score(a) - score(b))[0] ?? null;
}

/** Fetch + parse a timedtext track. Tries json3 first, falls back to XML. */
export async function fetchCaptions(
  trackBaseUrl: string,
  fetchImpl: typeof fetch = fetch,
): Promise<CaptionCue[] | null> {
  const sep = trackBaseUrl.includes("?") ? "&" : "?";
  const jsonUrl = `${trackBaseUrl}${sep}fmt=json3`;
  const res = await fetchImpl(jsonUrl);
  if (!res.ok) return null;
  const body = await res.text();
  if (body.trimStart().startsWith("{")) {
    return parseJson3(body);
  }
  return parseCaptionsXml(body);
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
}

/** json3 shape: {"events":[{"tStartMs":0,"dDurationMs":1500,"segs":[{"utf8":"hi"}]}]} */
export function parseJson3(body: string): CaptionCue[] | null {
  let parsed: { events?: Json3Event[] };
  try {
    parsed = JSON.parse(body) as { events?: Json3Event[] };
  } catch {
    return null;
  }
  const events = parsed.events ?? [];
  const cues: CaptionCue[] = [];
  for (const ev of events) {
    const text = (ev.segs ?? []).map((s) => s.utf8 ?? "").join("").replace(/\n/g, " ").trim();
    if (!text || ev.tStartMs === undefined) continue;
    cues.push({
      start: ev.tStartMs / 1000,
      duration: (ev.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  return cues.length ? cues : null;
}

/** Legacy timedtext XML: <text start="12.4" dur="2.1">body</text> */
export function parseCaptionsXml(xml: string): CaptionCue[] | null {
  const cues: CaptionCue[] = [];
  const re = /<text\b[^>]*\bstart="([\d.]+)"[^>]*\bdur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    // Strip raw inline tags (<s>, <c>) BEFORE decoding entities, otherwise
    // decoded &lt;...&gt; would be mistaken for markup and erased.
    const text = decodeEntities(m[3]!.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();
    if (!text) continue;
    cues.push({ start: parseFloat(m[1]!), duration: parseFloat(m[2]!), text });
  }
  return cues.length ? cues : null;
}

export function decodeEntities(s: string): string {
  return s
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(parseInt(code, 10)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

/**
 * Cue list -> plain transcript. Joins cues into sentences, dropping exact
 * repeated lines that auto-captions sometimes emit (rolling captions).
 */
export function cuesToTranscript(cues: readonly CaptionCue[]): string {
  const sentences: string[] = [];
  let buf = "";
  let lastEmitted = "";
  for (const cue of cues) {
    const text = cue.text.trim();
    if (!text || text === lastEmitted) continue;
    lastEmitted = text;
    buf = buf ? `${buf} ${text}` : text;
    if (/[.!?…。]$/.test(text)) {
      sentences.push(buf);
      buf = "";
    }
  }
  if (buf) sentences.push(buf);
  return sentences.join("\n");
}

/**
 * Timestamped topic index: group cues into ~45s blocks and prefix each with
 * [mm:ss] so the model can cite positions and users can jump around.
 */
export function buildTimestampIndex(cues: readonly CaptionCue[], blockSeconds = 45): string {
  const lines: string[] = [];
  let blockStart = 0;
  let parts: string[] = [];
  const flush = () => {
    const text = parts.join(" ").trim();
    if (text) lines.push(`[${formatMinSec(blockStart)}] ${text}`);
    parts = [];
  };
  for (const cue of cues) {
    if (parts.length && cue.start - blockStart >= blockSeconds) {
      flush();
      blockStart = cue.start;
    }
    parts.push(cue.text.trim());
  }
  flush();
  return lines.join("\n");
}

function formatMinSec(seconds: number): string {
  const s = Math.max(0, Math.floor(seconds));
  const mm = String(Math.floor(s / 60)).padStart(2, "0");
  const ss = String(s % 60).padStart(2, "0");
  return `${mm}:${ss}`;
}

/**
 * Split long transcripts into <=maxChars chunks at sentence boundaries
 * (never mid-sentence unless a single sentence exceeds the budget).
 */
export function chunkTranscript(transcript: string, maxChars = 12000): string[] {
  const sentences = transcript.split(/(?<=[.!?…。])\s+/).filter(Boolean);
  if (!sentences.length) return [];
  const chunks: string[] = [];
  let cur = "";
  for (const sentence of sentences) {
    if (sentence.length > maxChars) {
      if (cur) {
        chunks.push(cur);
        cur = "";
      }
      // hard-split monster sentences
      for (let i = 0; i < sentence.length; i += maxChars) {
        chunks.push(sentence.slice(i, i + maxChars));
      }
      continue;
    }
    if (cur.length + 1 + sentence.length > maxChars && cur) {
      chunks.push(cur);
      cur = sentence;
    } else {
      cur = cur ? `${cur} ${sentence}` : sentence;
    }
  }
  if (cur) chunks.push(cur);
  return chunks;
}
